### PR TITLE
Exp refactor

### PR DESCRIPTION
**Pull request by chedburgh**
This is quite a large refactor. It creates a new libhbdpp, that is not compatible with existing device servers and modules. hdbpp_es/cm have branches to become compatible with this version. Rework for other backends is required.

Highlights:

* Renamed API
* Improved build system
* Support features, such as batch insertion
* Code refactor:
  * Header install path is hdb++ (this is a generic path that other projects will use)
  * Split single source/header into client/backend headers.
  * Updated build system (multiple project integration work)
  * Modernize c++ code.
  * Observe namespaces in headers
  * Added code to hdbpp namespace
  * Pass by reference for performance where possible without changing API
* Combined README and INSTALL files
* Removed TTL from add attribute function.
* Removed some unused functions.
* HdbClientData class, this should be in the Event Subscriber

This is the first of several large pull requests for hdb++ projects.

### CODE REVIEW

**Review by lorenzopivetta — APPROVED** [review]
Looks good to me.

**Review by lorenzopivetta — APPROVED** [review]
I've not tested running the device, but the build environment works!
Looks good to me.

**Review by gscalam — APPROVED** [review]
OK for me.

**Review by dlacoste-esrf — APPROVED** [review]

**Review by bourtemb — CHANGES_REQUESTED** [review]
This PR has a conflict on cmake/ReleaseVersion.cmake (which was removed in the PR and updated in the meantime in master) which cannot be solved from Github interface.
This conflict needs to be fixed at the command line.

**Pull request merged**
